### ISSUE TITLE
Stress tests don't seem to be working in CI

### ISSUE THREAD

**Issue by Trott** [nodejs/testing#10]
I haven't been able to get a stress test going on pi1-raspbian-wheezy for several days now. I imagine this is something @joaocgreis would have to take a look at, and of course he may be busy with other things. Not sure there's much else to do about it other than maybe seeing if anyone else on @nodejs/build can take a look.

**Comment by rvagg** [comment]
@Trott can you point us to a job where it's not working? I'm missing context on this I think.

**Comment by Trott** [comment]
@rvagg Sure:
- https://ci.nodejs.org/job/node-stress-single-test/365/nodes=pi1-raspbian-wheezy/
- https://ci.nodejs.org/job/node-stress-single-test/362/nodes=pi1-raspbian-wheezy/
- https://ci.nodejs.org/job/node-stress-single-test/361/nodes=pi1-raspbian-wheezy/
- https://ci.nodejs.org/job/node-stress-single-test/360/nodes=pi1-raspbian-wheezy/

**Comment by rvagg** [comment]
@Trott should be fixed now, running your job (only 100 times, feel free to start another if you like) @ https://ci.nodejs.org/job/node-stress-single-test/366/nodes=pi1-raspbian-wheezy/console

@joaocgreis I turned on the regex check for the tasks in that job so that the Windows bat stuff only runs on Windows and the Bash bit only runs on everything else. (also started a Windows job here: https://ci.nodejs.org/job/node-stress-single-test/367/nodes=win2008r2/console although I haven't waited for it to finish before posting it, might be worthwhile double-checking!).

**Comment by rvagg** [comment]
Oh, that Windows build is _not_ happy .. not sure it's to do with this change, however, @joaocgreis would you mind having a look please?

**Comment by joaocgreis** [comment]
@rvagg your changes LGTM. I ran https://ci.nodejs.org/job/node-stress-single-test/368/nodes=win-vs2015/console and it was happy, the `win-vs2015` label forced it to run in the slaves that we currently use to build the test-commit job. The problem with your run was that it used a slave that is having some problem with Visual Studio, I'll have to investigate it. The test-commit job is not affected by it.

**Comment by Trott** [comment]
All is working A-OK for me again on CI stress tests. Thanks for the help, @rvagg and @joaocgreis!
